package constants

const (
	USER_INDEX  = "user"
	POST_INDEX  = "post"
	ES_URL      = "http://IP_ADDRES_ELASTICSEARCH_INSTALLED:9200"
	ES_USERNAME = "YOUR_ELASTICSEARCH_USERNAME"
	ES_PASSWORD = "YOUR_ELASTICSEARCH_PASSWORD"
	GCS_BUCKET  = "YOUR_GCS_BUCKET_NAME"
)
